import Head from 'next/head'
import AddTask from '../components/AddTask';
import TaskList from '../components/TaskList';
import { TasksProvider } from '../components/TasksContext';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <TasksProvider>
      <h1>Day off in Kyoto</h1>
      <AddTask />
      <TaskList />
    </TasksProvider>
    </div>
  )
}
